[config]

[templates.gtk3]
input_path = './matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/dark-colors.css'

[templates.gtk4]
input_path = './matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/dark-colors.css'

[templates.kcolorscheme]
input_path = './matugen/templates/matugen-kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/DarkMatugen.colors'